name: demo_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  cached_network_image: ^3.1.0+1
  logger: ^1.1.0
  firebase_core: "^1.10.0"
  google_sign_in: ^5.2.1
  firebase_auth: ^3.2.0
  cloud_firestore:
  fluttertoast: ^8.0.9
  get:
  badges:
  confetti: ^0.7.0
  lottie: ^1.4.1
  adaptive_action_sheet: ^2.0.0
  flutter_signin_button: ^2.0.0

  flutter_lints: ^2.0.0
  encrypt: ^5.0.1
  selectable: ^0.2.4

  stop_watch_timer: ^1.5.0
  shared_preferences:
  flutter_slidable: ^2.0.0
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
